export interface MCPServerWorkflow {
  workflow_id: string;
  tool_name: string; // Name to expose as MCP tool
  tool_description: string; // Description for the MCP tool
}

export type MCPServerAuthType = "api_key" | "oauth2";

/**
 * Auth metadata from the management API (matches stored auth_values minus client secret).
 */
export interface MCPServerPublicAuthValues {
  /** Present and masked (e.g. ***) when api_key auth is configured */
  api_key?: string | null;
  /** Full URL to OIDC discovery (openid-configuration); token/JWKS URLs come from this document */
  oauth2_issuer_url?: string | null;
  /** Space-separated scopes (optional inbound scope/scp check) */
  oauth2_scope?: string | null;
  /** Comma-separated allowlist for JWT aud; empty / omitted = do not enforce aud */
  oauth2_audience?: string | null;
  /** Decrypted client id for edit forms (management API only) */
  oauth2_client_id?: string | null;
  /** True when a client secret is stored; secret is never returned */
  oauth2_client_secret_set?: boolean;
}

export interface MCPServer {
  id: string;
  name: string;
  url?: string; // MCP server URL (generated by backend)
  auth_type: MCPServerAuthType;
  auth_values: MCPServerPublicAuthValues;
  workflows: MCPServerWorkflow[]; // Array of workflows to expose as tools
  description?: string | null;
  is_active: number;
  is_deleted: number;
  created_at: string; // ISO string
  updated_at: string; // ISO string
}

export interface MCPServerCreatePayload {
  name: string;
  auth_type: MCPServerAuthType;
  api_key?: string;
  /** Must match application id inside inbound access tokens (azp / client_id / appid, etc.) */
  oauth2_client_id?: string;
  oauth2_client_secret?: string;
  /** Full URL to /.well-known/openid-configuration (preferred) */
  oauth2_issuer_url?: string;
  /** Space-separated scopes for optional JWT scope/scp validation */
  oauth2_scope?: string;
  /** Optional; comma-separated JWT aud allowlist */
  oauth2_audience?: string;
  workflows: MCPServerWorkflow[];
  description?: string;
  is_active?: number;
}

export interface MCPServerUpdatePayload {
  name?: string;
  auth_type?: MCPServerAuthType;
  api_key?: string;
  oauth2_client_id?: string;
  oauth2_client_secret?: string;
  oauth2_issuer_url?: string;
  oauth2_scope?: string;
  oauth2_audience?: string;
  workflows?: MCPServerWorkflow[];
  description?: string;
  is_active?: number;
}
