export interface MCPServerWorkflow {
  workflow_id: string;
  tool_name: string; // Name to expose as MCP tool
  tool_description: string; // Description for the MCP tool
}

export interface MCPServer {
  id: string;
  name: string;
  url?: string; // MCP server URL (generated by backend)
  api_key: string; // Encrypted/stored securely
  workflows: MCPServerWorkflow[]; // Array of workflows to expose as tools
  description?: string | null;
  is_active: number;
  is_deleted: number;
  created_at: string; // ISO string
  updated_at: string; // ISO string
}

export interface MCPServerCreatePayload {
  name: string;
  api_key: string;
  workflows: MCPServerWorkflow[];
  description?: string;
  is_active?: number;
}

export interface MCPServerUpdatePayload {
  name?: string;
  api_key?: string; // Optional - only update if provided
  workflows?: MCPServerWorkflow[];
  description?: string;
  is_active?: number;
}

