export type HTTPMethod = 'GET' | 'POST';
export type WebhookType = 'slack' | 'whatsapp' | 'generic';

export interface Webhook {
  id: string;
  name: string;
  url: string;
  method: HTTPMethod;
  headers: Record<string, string>;
  secret?: string | null;
  description?: string | null;
  is_active: number;
  is_deleted: number;
  webhook_type: WebhookType;
  agent_id?: string | null;
  app_settings_id?: string | null;
  created_at: string; // ISO string
  updated_at: string; // ISO string
}

export interface WebhookCreatePayload {
  name: string;
  url?: string; // URL is generated by backend, optional in create
  method: HTTPMethod;
  headers?: Record<string, string>;
  secret?: string;
  description?: string;
  is_active?: number;
  webhook_type?: WebhookType;
  agent_id?: string;
  app_settings_id?: string;
  base_url?: string;
}

export interface WebhookUpdatePayload {
  name?: string;
  url?: string;
  method?: HTTPMethod;
  headers?: Record<string, string>;
  secret?: string;
  description?: string;
  is_active?: number;
  webhook_type?: WebhookType;
  agent_id?: string;
  app_settings_id?: string;
}
