"""add_mcp_servers_tables

Revision ID: bb81948b4490
Revises: b152ce8a0a1c
Create Date: 2025-12-22 14:20:34.538232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb81948b4490'
down_revision: Union[str, None] = 'b152ce8a0a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='unique_name_user')
    )
    op.create_index('idx_api_key_hash', 'mcp_servers', ['api_key_hash'], unique=False)
    op.create_index('idx_user_active', 'mcp_servers', ['user_id', 'is_active', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_mcp_servers_api_key_hash'), 'mcp_servers', ['api_key_hash'], unique=False)
    op.create_table('mcp_server_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_description', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcp_server_id', 'tool_name', name='unique_server_tool_name')
    )
    op.create_index('idx_workflow', 'mcp_server_workflows', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow', table_name='mcp_server_workflows')
    op.drop_table('mcp_server_workflows')
    op.drop_index(op.f('ix_mcp_servers_api_key_hash'), table_name='mcp_servers')
    op.drop_index('idx_user_active', table_name='mcp_servers')
    op.drop_index('idx_api_key_hash', table_name='mcp_servers')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
