"""add hashed value to validate auth

Revision ID: 48df9c298dd9
Revises: d3a7fd9d0d3a
Create Date: 2025-05-29 14:40:24.971227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48df9c298dd9'
down_revision: Union[str, None] = 'd3a7fd9d0d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('hashed_value', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'hashed_value')
    # ### end Alembic commands ###
