"""remove masked_api_key field in api_keys table

Revision ID: d3a7fd9d0d3a
Revises: 521bf4492593
Create Date: 2025-05-29 12:35:31.293444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a7fd9d0d3a'
down_revision: Union[str, None] = '521bf4492593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'masked_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('masked_value', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
