"""unlimit audit

Revision ID: b6ebad5ee662
Revises: bb81948b4490
Create Date: 2025-12-22 16:38:19.814290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6ebad5ee662"
down_revision: Union[str, None] = "bb81948b4490"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_log",
        "json_changes",
        existing_type=sa.VARCHAR(length=4000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_log",
        "json_changes",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=4000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
